kinesis: "Kinesis" {
  icon: https://icons.terrastruct.com/aws%2FAnalytics%2FAmazon-Kinesis.svg
  shape: image
}

cdc: "CDC" {
  icon: https://icons.terrastruct.com/aws%2FDatabase%2FAWS-Database-Migration-Service_light-bg.svg
  shape: image
}

direction: right
transaction: "Transactional outbox" {
  app: "App" {
    icon: https://icons.terrastruct.com/dev%2Fnodejs.svg  
    shape: image
  }

  db: "Database" {
    icon: https://icons.terrastruct.com/essentials%2F117-database.svg
    shape: image
  }

  app -> db: App stores data
  app -> db: App stores events
}
transaction.db -> cdc: Use replica to collect events
cdc -> kinesis: Send events to Kinesis
