kinesis: "Kinesis" {
  icon: https://icons.terrastruct.com/aws%2FAnalytics%2FAmazon-Kinesis.svg
  shape: image
}

app: "App" {
  icon: https://icons.terrastruct.com/dev%2Fnodejs.svg  
  shape: image
}

db: "Database" {
  icon: https://icons.terrastruct.com/essentials%2F117-database.svg
  shape: image
}

eventBridge: "Event Bridge" {
  icon: https://icons.terrastruct.com/aws%2FApplication%20Integration%2FAmazon-EventBridge.svg
  shape: image
}

direction: right
app -> db: App stores events in DB
db -> eventBridge: Atlas sends event
eventBridge -> kinesis: Send events to Kinesis
