kinesis: "Kinesis" {
  icon: ../icons/aws/kinesis.svg
  shape: image
}

cdc: "CDC" {
  icon: ../icons/aws/dms.svg
  shape: image
}

direction: right
transaction: "Transactional outbox" {
  app: "App" {
    icon: ../icons/nodejs.svg
    shape: image
  }

  db: "Database" {
    icon: ../icons/database.png
    shape: image
  }

  app -> db: App stores data
  app -> db: App stores events
}
transaction.db -> cdc: Use replica to collect events
cdc -> kinesis: Send events to Kinesis
