kinesis: "Kinesis" {
  icon: https://icons.terrastruct.com/aws%2FAnalytics%2FAmazon-Kinesis.svg
  shape: image
}

app: "App" {
  icon: https://icons.terrastruct.com/dev%2Fnodejs.svg  
  shape: image
}

db: "Database" {
  icon: https://icons.terrastruct.com/essentials%2F117-database.svg
  shape: image
}

direction: right
app -> kinesis: App sends events to kinesis
app -> db: App stores events in DB
Worker -> kinesis: Send unsent events to Kinesis
db <- Worker: pull unsent events
