#!/bin/bash

d2 --layout elk app-to-kinesis.d2 out/app-to-kinesis.png
d2 --layout elk app-outbox-cdc-kinesis.d2 out/app-outbox-cdc-kinesis.png
d2 --layout elk app-outbox-atlas-kinesis.d2 out/app-outbox-atlas-kinesis.png
